name: magaza_yonetimi
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  mobile_scanner: ^3.5.7
  shimmer: ^3.0.0
  lottie: ^2.6.0
  cached_network_image: ^3.3.0
  http: ^1.1.0
  flutter_svg: ^2.0.9
  flutter_animate: ^4.4.0
  shared_preferences: ^2.2.2
  provider: ^6.0.0
  google_fonts: ^6.2.1
  flutter_tts: ^3.8.5
  speech_to_text: 7.0.0
  flutter_cache_manager: ^3.3.0
  connectivity_plus: ^5.0.2
  excel: ^2.1.0
  equatable: ^2.0.5
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  flutter_slidable: ^4.0.0
  table_calendar: ^3.0.9
  flutter_colorpicker: ^1.1.0
  audioplayers: ^6.1.0
  logging: ^1.2.0
  timeago: ^3.6.1
  flutter_staggered_animations: ^1.1.1
  app_settings: ^6.1.1
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/a101_icon.png"

dependency_overrides:
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
      ref: master

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icon/a101_icon.png
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
